apiVersion: v1
kind: Secret
metadata:
  name: secret-dwiki
type: Opaque
data:
  ob-core-db: U2VydmVyPXRjcDpvbi1ib2FyZC1hc3RyYS1zdGFyLmRhdGFiYXNlLndpbmRvd3MubmV0LDE0MzM7SW5pdGlhbCBDYXRhbG9nPWR3aWtpLWF1dGgtZGI7UGVyc2lzdCBTZWN1cml0eSBJbmZvPUZhbHNlO1VzZXIgSUQ9YWRtaW5hZG1pbjtQYXNzd29yZD1FY29tUEBzc3cwcmQ7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPUZhbHNlO0VuY3J5cHQ9VHJ1ZTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPUZhbHNlO0Nvbm5lY3Rpb24gVGltZW91dD0zMDs=